Lesson5
am-20/Kolesa-Upgrade-FE-2021 pull request #5
Opened 2021-10-11 04:18 UTC by am-20

Catalog & modals JS

2021-10-11 04:20 UTC, am-20 commented
С tabs и каталогом товаров вроде разобралась, а вот с модальным окном всё не так хорошо. 

Проблемы, которые возникли:

1. Те карточки товаров, что я создаю через js, я не могу использовать. Указываю их класс через querySelector(или класс кнопки), но их не находит. Следовательно addEvenListener не работает. 
Хотя, если я ввожу те же строчки кода через консоль, то всё работает.

2. Присвоить каждое модальное окно к одной карточке. Я думаю это нужно сделать как-то перебором массивов, но еще не разобралась как именно. 

3. Есть старая проблемка в модалке с checkbox. Думаю поменять их на button, чтобы работали также, как tabs.

Как-то так :)
Надеюсь, что к следующему дедлайну со всем разберусь!

2021-10-11 05:49 UTC, wizzout requested changes
Спасибо за ДЗ, есть большие проблемы

- при загрузке не выведены все товары
- при открытии модалки все ломается и невозможно закрыть
- при смене категории уже ничего не открывается (ты и так об этом знала но решила запушить лишь бы успеть в мягкий дедлайн — не надо так) 

Также пройдись по комментариям и постарайся поравить

дедлайн 12 октября 12:00

![Screen Shot 2021-10-11 at 11 49 38](https://user-images.githubusercontent.com/22858436/136739432-cfc90bb5-e5f3-4edc-a7a7-fcf64127a7be.png)

2021-10-11 05:49 UTC, wizzout commented on src/js/main.js
> +        catalog.removeChild(catalog.lastElementChild);
почему через removeChild? почему не заменить содержимое на '' ?

2021-10-11 05:49 UTC, wizzout commented on src/js/main.js
> +        catalog.removeChild(catalog.lastElementChild);
каждое удаление вызывает перерисовку - лишняя работа браузера

2021-10-11 05:49 UTC, wizzout commented on src/js/main.js
> +        tabsBtn.forEach((x) => {
почему бы просто не поискать такой элемент и не удалить ему класс? 

И что делать если кликнули по активному - весь код все равно выполнится?

2021-10-11 05:49 UTC, wizzout commented on src/js/main.js
> +            const all = clothes.concat(accessories);
надо ли это делать каждый раз? у тебя меняются массивы в процессе работы?

2021-10-11 05:49 UTC, wizzout commented on src/js/main.js
> +            accessories.sort(newSort);
зачем каждый раз сортировать массив - почитай про особенность Array.sort

2021-10-11 05:49 UTC, wizzout commented on src/js/main.js
> +        details: 'Бутылка для воды с трубочкой',
быть может лучше перенести это поле в accessories, чем заниматься переписыванием?

2021-10-11 05:49 UTC, wizzout commented on src/js/main.js
> +const accessoriesModals = [
константы принято в начале файла размещать раз они используются прям в корне и глобальны

2021-10-11 05:49 UTC, wizzout commented on src/js/main.js
> +buyBtn.forEach((btn) => {
ты слушатель вешаешь один раз - при загрузке страницы - но ведь ты удаляешь карточке при смене категорий - соотвественно и элементы которые тут слушают тоже удаляются. Поэтому не работает

2021-10-11 05:49 UTC, wizzout commented on src/js/main.js
> +        accessoriesModals.forEach(addModal);
Зачем добавлять все модалки? когда тебе нужна только одна?

2021-10-11 05:49 UTC, wizzout commented on src/js/main.js
> +        clothesModals.forEach(addModal);
Зачем добавлять все модалки? когда тебе нужна только одна?

2021-10-12 04:40 UTC, am-20 commented
> почему через removeChild? почему не заменить содержимое на '' ?  

исправлено

2021-10-12 04:40 UTC, am-20 commented
> почему бы просто не поискать такой элемент и не удалить ему класс? 

И что делать если кликнули по активному - весь код все равно выполнится?  

исправлено

2021-10-12 04:41 UTC, am-20 commented
> надо ли это делать каждый раз? у тебя меняются массивы в процессе работы?  

переместила в коде

2021-10-12 04:42 UTC, am-20 commented
> зачем каждый раз сортировать массив - почитай про особенность Array.sort  

это тоже переместила

2021-10-12 04:42 UTC, am-20 commented
> быть может лучше перенести это поле в accessories, чем заниматься переписыванием? 

 

перенесла в accessories

2021-10-12 04:48 UTC, am-20 commented
> ты слушатель вешаешь один раз - при загрузке страницы - но ведь ты удаляешь карточке при смене категорий - соотвественно и элементы которые тут слушают тоже удаляются. Поэтому не работает 

с открытием модалки более менее разобралась, а вот с закрытием не очень. 

не поняла, как работать с модал, если добавлять её таким образом через js :(

2021-10-12 05:24 UTC, wizzout commented
> * при загрузке не выведены все товары
Не исправлено

2021-10-12 06:00 UTC, wizzout approved these changes
Можешь мержить и добиваться работоспособности уже отдельно от этого пр. Жаль что не вышло решить всех проблем. Но за старания +

2021-10-12 06:00 UTC, wizzout commented on src/js/main.js
> +// const buyBtn = document.querySelectorAll('.card__btn');
мертвый код

2021-10-12 06:00 UTC, wizzout commented on src/js/main.js
> +const accessoriesModals = [
зачем нужны эти массивы? Все данные уже есть в массивах для карточек.

2021-10-12 06:00 UTC, wizzout commented on src/js/main.js
> +            clothes.forEach(addCard);
делается функция допустим updateProducts в нее передаем список продуктов (допустим all);

Внутри  неё очистить текущий отрисованный список, пройтись циклом по массиву и создавать отдельно карточку и отдельно модалку;  и еще было бы идеально в этом цикле добавлять слушатель клика по кнопке в карточке и связать его с модалкой. А еще лучше иметь одну модалку и менять в ней контент по клику на кнопку. 

И все это в одной

2021-10-12 06:00 UTC, wizzout commented on src/js/main.js
> +        [...tabsBtn].find(btn => btn.classList.contains('tabs__btn--active')).classList.remove('tabs__btn--active');
если пользователь кликнул по активному табу ничего не должно происходить

2021-10-19 16:01 UTC, merged